# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI/CD with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: spotify-clone
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
       # --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
           
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.15
      uses: actions/setup-java@v1
      with:
        java-version: 1.15
    - name: Build and Test with Maven
      run: mvn -B package --file pom.xml
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: application-package
        path: /**/target/spotify-clone-0.0.1-SNAPSHOT.jar

    - name: download application package
      uses: actions/download-artifact@v2
      with:
        name: application-package

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: bartofzo013/spotify-clone
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
